name: Unity CI/CD

on:
  push:
    branches:
        - main
  pull_request: 
    branches: 
        - main

jobs:
  build:
    name: Build and Test Unity Game
    runs-on: ubuntu-latest  # Utilisation de Linux pour exécuter Unity Headless

    steps:      
        - name: Checkout Repository
          uses: actions/checkout@v3

      
        - name: Cache Unity Library
          uses: actions/cache@v3
          with:
            path: Library
            key: Library-${{ runner.os }}-${{ hashFiles('Packages/manifest.json') }}
            restore-keys: |
                Library-${{ runner.os }}-

        - name: Request Activation File
          uses: game-ci/unity-activator@v2
          with:
            unityVersion: 6000.0.34f1
      
        - name: Install Unity
          uses: game-ci/unity-builder@v2
          with:
            unityVersion: 6000.0.34f1  # Change avec ta version Unity
            targetPlatform: StandaloneWindows64  # Windows, WebGL, Android, etc.

      
        - name: Run Unit Tests
          uses: game-ci/unity-test-runner@v2
          with:
            unityVersion: 6000.0.34f1

      
        - name: Build Game
          uses: game-ci/unity-builder@v2
          with:
            unityVersion: 6000.0.34f1
            targetPlatform: StandaloneWindows64

      
        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Unity-Build
            path: build/StandaloneWindows64